name: Hello, World Demo by Oskdin!
description: Greet someone and record the time
author: Oskdin Actions

# Define your inputs here.
inputs:
  who-to-greet: # id of input
    description: Who to greet
    required: true
    default: World

# Define your outputs here.
outputs:
  time: # id of output
    description: The time we greeted you

runs:
  using: node20
  main: index.js
branding:
  icon: message-square
  color: blue
